import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import {
  getDocument,
  GlobalWorkerOptions
} from 'pdfjs-dist/legacy/build/pdf.mjs'
import type { TextItem } from 'pdfjs-dist/types/src/display/api'

// The extension bundler (directus-extension build) inlines every module into a
// single dist/api.js, which breaks pdfjs-dist's own worker path guess - it looks
// for "pdf.worker.mjs" next to the bundle, which does not exist there (only in
// node_modules). Resolve the real file explicitly via Node's module resolution
// (works because node_modules/pdfjs-dist itself is not bundled away) rather than
// letting pdfjs-dist guess a path relative to the bundled file's location.
GlobalWorkerOptions.workerSrc = pathToFileURL(
  createRequire(import.meta.url).resolve(
    'pdfjs-dist/legacy/build/pdf.worker.mjs'
  )
).href

// Generic line/paragraph extraction for an SMD "Dossier" PDF. Both the
// Regionaljournal (dossiers/pdf-parser.ts) and Punkt6 (punkt6/pdf-parser.ts)
// dossier PDFs come from the same SMD system - identical two-column layout,
// identical footer, identical "HH:MM:SS text" transcript convention - so this
// module holds only the format-agnostic mechanics; show-specific markers
// (headline/date headers, marker text) stay in each domain's own pdf-parser.ts.
//
// Ported from the Python PoC's pdf_parser.py, which used PyMuPDF's block/bbox API.
// pdfjs-dist's getTextContent() gives a flatter primitive: one positioned text item
// per visual LINE (verified against real sample PDFs - a wrapped paragraph arrives
// as several same-x-column items at decreasing y, not pre-grouped into paragraphs
// the way PyMuPDF grouped them). Two things PyMuPDF gave for free had to be
// rebuilt here:
//
//   1. Column order: split lines by x0 < pageWidth/2, read all of the left column
//      top-to-bottom then all of the right column top-to-bottom.
//   2. Paragraph/block grouping: for the timestamped transcript body, the
//      `HH:MM:SS` prefix itself unambiguously marks a new paragraph, so no gap
//      heuristic is needed there. For an untimestamped preamble (headline/teaser
//      text), a paragraph boundary was found to reliably correlate with a
//      larger-than-normal line gap - see PARAGRAPH_GAP_RATIO.

export interface Paragraph {
  timestamp: string // "HH:MM:SS"
  seconds: number
  text: string
}

export interface Line {
  y: number
  x0: number
  fontSize: number
  text: string
}

// Both shows' PDFs share this exact footer, generated by the same SMD system.
export const SMD_FOOTER_RE = /^Dossier - Bello Bajour -/
// The footer's page number sits far enough right to land in the *right* text
// column on its own (confirmed against real sample PDFs: same y as the
// "Dossier - Bello Bajour -" text, but a separate item at high x) - a lone digit
// line is never real transcript content, so it's safe to drop outright.
export const SMD_PAGE_NUMBER_RE = /^\d+$/
export const TIMESTAMP_RE = /^(\d{2}):(\d{2}):(\d{2})\s+(.*)$/s

// Calibrated against the real Regionaljournal sample PDFs: a gap bigger than this
// multiple of the preceding line's font size starts a new (untimestamped) block.
export const PARAGRAPH_GAP_RATIO = 1.4

function isTextItem(item: unknown): item is TextItem {
  return typeof item === 'object' && item !== null && 'str' in item
}

interface RawItem {
  x: number
  y: number
  fontSize: number
  str: string
}

/**
 * Groups same-column items into lines by rounding y with a small tolerance.
 *
 * Must run PER COLUMN, never across the whole page: the left and right columns
 * routinely have text at the same height (confirmed against real sample PDFs), so
 * grouping by y alone - before splitting into columns - merges a left-column line
 * and an unrelated right-column line into one garbled row, silently swallowing
 * whichever one didn't win the resulting text.
 */
function groupIntoLines(items: RawItem[]): Line[] {
  const rows = new Map<number, RawItem[]>()
  for (const item of items) {
    const key = Math.round(item.y * 2) / 2 // half-point tolerance for same-line items
    const row = rows.get(key)
    if (row) row.push(item)
    else rows.set(key, [item])
  }

  return [...rows.entries()]
    .map(([y, rowItems]) => {
      const sorted = [...rowItems].sort((a, b) => a.x - b.x)
      const first = sorted[0]
      const text = sorted
        .map((i) => i.str)
        .join(' ')
        .replace(/\s+/g, ' ')
        .trim()
        .normalize('NFKC')
      return {
        y,
        x0: first ? first.x : 0,
        fontSize: first ? first.fontSize : 10,
        text
      }
    })
    .filter((l) => l.text !== '')
}

export type PdfPage = Awaited<
  ReturnType<Awaited<ReturnType<typeof getDocument>['promise']>['getPage']>
>

export async function extractOrderedLines(page: PdfPage): Promise<Line[]> {
  const viewport = page.view // [x0, y0, x1, y1] - always exactly 4 elements
  const pageWidth = viewport[2]! - viewport[0]!
  const mid = pageWidth / 2

  const content = await page.getTextContent()
  const leftItems: RawItem[] = []
  const rightItems: RawItem[] = []

  for (const raw of content.items) {
    if (!isTextItem(raw)) continue
    const str = raw.str
    if (str.trim() === '') continue

    const x = raw.transform[4] as number
    const y = raw.transform[5] as number
    const fontSize = Math.hypot(
      raw.transform[0] as number,
      raw.transform[1] as number
    )
    const item = { x, y, fontSize, str }
    ;(x < mid ? leftItems : rightItems).push(item)
  }

  const left = groupIntoLines(leftItems).sort((a, b) => b.y - a.y)
  const right = groupIntoLines(rightItems).sort((a, b) => b.y - a.y)
  return [...left, ...right]
}

export function clusterIntoBlocks(
  lines: Line[],
  gapRatio: number = PARAGRAPH_GAP_RATIO
): Line[][] {
  const blocks: Line[][] = []
  let current: Line[] = []

  for (const line of lines) {
    const prev = current.at(-1)
    if (prev && (prev.y - line.y) / prev.fontSize > gapRatio) {
      blocks.push(current)
      current = []
    }
    current.push(line)
  }
  if (current.length > 0) blocks.push(current)
  return blocks
}

export function joinWithHyphenAwareness(pieces: string[]): string {
  let text = ''
  for (const piece of pieces) {
    if (text === '') text = piece
    else if (text.endsWith('-')) text += piece
    else text += ' ' + piece
  }
  return text
}

export function joinBlockLines(lines: Line[]): string {
  return joinWithHyphenAwareness(lines.map((l) => l.text))
}

// A trailing marker with no content after it (e.g. a Punkt6 PDF's final
// "00:13:33" with nothing more spoken) - TIMESTAMP_RE requires at least one
// whitespace character after the digits, so a bare timestamp never matches it
// and would otherwise get glued onto the previous paragraph's text as noise.
const BARE_TIMESTAMP_RE = /^\d{2}:\d{2}:\d{2}$/

export function reflowParagraphs(lines: Line[]): Paragraph[] {
  const paragraphs: Paragraph[] = []

  for (const line of lines) {
    if (BARE_TIMESTAMP_RE.test(line.text)) continue

    const match = TIMESTAMP_RE.exec(line.text)
    if (match) {
      const [, h, m, s, rest] = match as unknown as [
        string,
        string,
        string,
        string,
        string
      ]
      paragraphs.push({
        timestamp: `${h}:${m}:${s}`,
        seconds: Number(h) * 3600 + Number(m) * 60 + Number(s),
        text: rest.trim()
      })
    } else {
      const last = paragraphs.at(-1)
      if (last) last.text = joinWithHyphenAwareness([last.text, line.text])
      // else: stray text before any timestamped paragraph started - dropped
    }
  }

  return paragraphs
}

export async function loadPdfDocument(buffer: Buffer) {
  const data = new Uint8Array(buffer)
  return getDocument({
    data,
    useWorkerFetch: false,
    disableFontFace: true,
    verbosity: 0
  }).promise
}
